image: python:3.7

stages:
  - collect

Collect data:
  stage: collect
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip
      - venv/

  before_script:
    - export RUN_DATE=`date +%Y-%m-%d_%H-%M`
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

  script:
    - python graph_collect.py --config $CONFIG_JSON --mongodb-config $MONGODB_CONFIG --graph-output graphs/graph_${RUN_DATE}.gexf -v $ACCOUNTS_CSV_SMALL

  artifacts:
    paths:
      - graphs/*.gexf
